# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: DarkGoldBar/DarkGoldBar.github.io
  branch: main
  base_url: https://sveltia-cms-auth.heigoapp.workers.dev
  auth_endpoint: /api/auth
media_folder: "static/images"
public_folder: "/images"
collections:
  - name: 'blog'
    label: '测试'
    folder: 'content/posts'
    media_folder: 'static/images/blog'
    public_folder: '/images/blog'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: '标题', name: 'title', widget: 'string' }
      - { label: '发布日期', name: 'date', widget: 'datetime' }
      - { label: '草稿', name: 'draft', widget: 'boolean', default: false }
      - { label: '描述', name: 'description', widget: 'string' }
      - { label: '正文', name: 'body', widget: 'markdown' }

  - name: 'code'
    label: '代码类'
    folder: 'content/posts/code'
    media_folder: 'static/images/code'
    public_folder: '/images/code'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: '标题', name: 'title', widget: 'string' }
      - { label: '发布日期', name: 'date', widget: 'datetime' }
      - { label: '草稿', name: 'draft', widget: 'boolean', default: false }
      - { label: '描述', name: 'description', widget: 'string' }
      - { label: '特色图片', name: 'featuredImage', widget: 'image'}
      - label: '标签'
        name: 'tags'
        widget: 'list'
        allow_add: true
        default: []
        field: { label: '标签', name: 'tag', widget: 'string' }
      - label: '分类'
        name: 'categories'
        widget: 'list'
        allow_add: true
        default: []
        field: { label: '分类', name: 'category', widget: 'string' }
      - { label: '作者', name: 'author', widget: 'string' }
      - { label: '作者链接', name: 'authorLink', widget: 'string' , pattern: ['mailto:.*', "必须以“mailto:”开头"]}
      - { label: '正文', name: 'body', widget: 'markdown' }

  - name: 'ljh'
    label: '刘建侯'
    folder: 'content/posts/ljh'
    media_folder: 'static/images/ljh'
    public_folder: '/images/ljh'
    create: true
    slug: 'ljh{{slug}}'
    fields:
      - { label: '标题', name: 'title', widget: 'string' }
      - { label: '发布日期', name: 'date', widget: 'datetime' }
      - { label: '草稿', name: 'draft', widget: 'boolean', default: false }
      - label: '标签'
        name: 'tags'
        widget: 'list'
        allow_add: true
        default: []
        field: { label: '标签', name: 'tag', widget: 'string' }
      - label: '分类'
        name: 'categories'
        widget: 'list'
        allow_add: true
        default: ['渭北英豪刘建侯']
        field: { label: '分类', name: 'category', widget: 'string' }
      - { label: '作者', name: 'author', widget: 'string' }
      - { label: '作者链接', name: 'authorLink', widget: 'string', pattern: ['mailto:.*', "必须以“mailto:”开头"] }
      - { label: '正文', name: 'body', widget: 'markdown' }
